# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    container_name: psych-net-db
    image: mongo:5.0.16
    restart: always
    volumes: 
      - ./mongo:/data/db
    ports: 
      - 4300:27017