// Generated by https://quicktype.io

export interface Appointment {
    _id:     string;
    date:    string;
    userId:  string;
    message: string;
    state:   string;
    removed: boolean;
    __v:     number;
}
