// Generated by https://quicktype.io

export interface RegisterResponse {
    fullName:    string;
    username:    string;
    email:       string;
    isActive:    boolean;
    _id:         string;
    __v:         number;
}
